### Login
POST http://localhost:8080/v1/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "securepassword"
}

> {% client.global.set("token", response.body.access_token) %}


### Logout
POST http://localhost:8080/v1/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY2MzIxMDcsInJvbGUiOiJjdXN0b21lciIsInVzZXJfaWQiOiI1NDgzNDQzNzI4MjgwNDUzMTUifQ.JNN6-z0K32o-n172XsskSuiRJmWKKtH-EZVaYEVBOQQ

### Create a User
POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "name": "Luisa Brune",
  "email": "luisa.brune3@example.com",
  "password": "securepassword"
}



### Update User
PUT http://localhost:8080/v1/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY4ODgzNjYsInJvbGUiOiJjdXN0b21lciIsInVzZXJfaWQiOiI1NDgzNDQzNzI4MjgwNDUzMTUifQ.bEei9vkBHJoE30dmErbZeyHx0NI4QWNmk0WafC8EqHo

{
  "name": "John Updated",
  "email": "john.updated@example.com"
}


### Create a property
POST http://localhost:8080/v1/property
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY4ODgzNjYsInJvbGUiOiJjdXN0b21lciIsInVzZXJfaWQiOiI1NDgzNDQzNzI4MjgwNDUzMTUifQ.bEei9vkBHJoE30dmErbZeyHx0NI4QWNmk0WafC8EqHo

