### Login
POST http://localhost:8080/v1/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "securepassword"
}

> {% client.global.set("token", response.body.access_token) %}


### Logout
POST http://localhost:8080/v1/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY2MzIxMDcsInJvbGUiOiJjdXN0b21lciIsInVzZXJfaWQiOiI1NDgzNDQzNzI4MjgwNDUzMTUifQ.JNN6-z0K32o-n172XsskSuiRJmWKKtH-EZVaYEVBOQQ

### Create a User
POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "name": "Isaac Newton",
  "email": "isaac.newton@email.com",
  "password": "securepassword"
}



### Update User
PUT http://localhost:8080/v1/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY5NDk5NDcsInJvbGUiOiJjdXN0b21lciIsInVzZXJfaWQiOiI1NDgzNDQzNzI4MjgwNDUzMTUifQ.xo6AM59D11KVbBaAlvoiF69VKNrlvN7Cds5rWArMhCU

{
  "name": "John Updated",
  "email": "john.updated@example.com"
}


### Create a property
POST http://localhost:8080/v1/property
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY5NTY1NDMsInJvbGUiOiJjdXN0b21lciIsInVzZXJfaWQiOiI1NDgzNDQzNzI4MjgwNDUzMTUifQ.0fLNLTXPGeOcPD4bp7W2j6SGSjki6Txctx7vozTXSm0

{
  "name": "Property 1",
  "description": "Description of property 1",
  "address": "123 Main St",
  "contact_email": "property1@email.com",
  "contact_phone": "123-456-7890"
}

