# Final stage for development
FROM golang:1.22

WORKDIR /app

# Install PostgreSQL client for database healthchecks
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

# Install reflex for auto-reloading
RUN go install github.com/cespare/reflex@latest

# Copy the necessary files
COPY . .

# Use reflex to watch for changes and reload
CMD ["reflex", "-c", "/app/reflex.conf"]
